name: For Fear Of Words
favicon: null
layout_spectrum: 0.35542
typography_spectrum: 0.37167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.023333127610385418
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
