name: For Fear Of Words
favicon: null
layout_spectrum: 0.37087
typography_spectrum: 0.37167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13140f'
    - '#ffffff'
    - '#534d41'
    - '#857b6f'
    - '#c3b2a2'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
